# คำสั่งรับค่าข้อความ ใช้ฟังก์ชั่น input()
# ***** ตัวแปร variable คือ ฃื่อที่ Dev ตั้งขึ้นมาเอง
fullname = input('ป้อนชื่อ: ')
mid_score = input('ป้อนคะแนนกลางภาค: ')
final_score = input('ป้อนคะแนนปลายภาค: ')
quiz_score = input('ป้อนคะแนนเก็บ: ')
print('---------------------')
print(f'สวัสดีคุณ : {fullname}')
print(f'คุณสอบได้คะแนนรวม : {int(mid_score) + int(final_score) + int(quiz_score)} คะแนน')
print('---------------------')